# MPG Cars

### Introduction:

The following exercise utilizes data from [UC Irvine Machine Learning Repository](https://archive.ics.uci.edu/ml/datasets/Auto+MPG)

### Step 1. Import the necessary libraries

In [1]:
import pandas as pd
import numpy as np

### Step 2. Import the first dataset [cars1](https://raw.githubusercontent.com/guipsamora/pandas_exercises/master/05_Merge/Auto_MPG/cars1.csv) and [cars2](https://raw.githubusercontent.com/guipsamora/pandas_exercises/master/05_Merge/Auto_MPG/cars2.csv).

   ### Step 3. Assign each to a variable called cars1 and cars2

In [2]:
cars1 = pd.read_csv("https://raw.githubusercontent.com/guipsamora/pandas_exercises/master/05_Merge/Auto_MPG/cars1.csv")
cars1.head()

,mpg,cylinders,displacement,horsepower,weight,acceleration,model,origin,car,Unnamed: 9,Unnamed: 10,Unnamed: 11,Unnamed: 12,Unnamed: 13
0,18.0,8,307,130,3504,12.0,70,1,chevrolet chevelle malibu,NaN,NaN,NaN,NaN,NaN
1,15.0,8,350,165,3693,11.5,70,1,buick skylark 320,NaN,NaN,NaN,NaN,NaN
2,18.0,8,318,150,3436,11.0,70,1,plymouth satellite,NaN,NaN,NaN,NaN,NaN
3,16.0,8,304,150,3433,12.0,70,1,amc rebel sst,NaN,NaN,NaN,NaN,NaN
4,17.0,8,302,140,3449,10.5,70,1,ford torino,NaN,NaN,NaN,NaN,NaN

In [3]:
cars2 = pd.read_csv("https://raw.githubusercontent.com/guipsamora/pandas_exercises/master/05_Merge/Auto_MPG/cars2.csv")
cars2.head()

,mpg,cylinders,displacement,horsepower,weight,acceleration,model,origin,car
0,33.0,4,91,53,1795,17.4,76,3,honda civic
1,20.0,6,225,100,3651,17.7,76,1,dodge aspen se
2,18.0,6,250,78,3574,21.0,76,1,ford granada ghia
3,18.5,6,250,110,3645,16.2,76,1,pontiac ventura sj
4,17.5,6,258,95,3193,17.8,76,1,amc pacer d/l

### Step 4. Oops, it seems our first dataset has some unnamed blank columns, fix cars1

In [4]:
cars1 = cars1.dropna(axis = 1, how = "all")    #  axis = 1 --> columns
cars1.head()

,mpg,cylinders,displacement,horsepower,weight,acceleration,model,origin,car
0,18.0,8,307,130,3504,12.0,70,1,chevrolet chevelle malibu
1,15.0,8,350,165,3693,11.5,70,1,buick skylark 320
2,18.0,8,318,150,3436,11.0,70,1,plymouth satellite
3,16.0,8,304,150,3433,12.0,70,1,amc rebel sst
4,17.0,8,302,140,3449,10.5,70,1,ford torino

### Step 5. What is the number of observations in each dataset?

In [5]:
cars1.shape

(198, 9)

In [6]:
cars2.shape

(200, 9)

### Step 6. Join cars1 and cars2 into a single DataFrame called cars

In [7]:
cars = pd.concat([cars1, cars2])
cars = cars.reset_index(drop=True)
cars.shape

(398, 9)

### Step 7. Oops, there is a column missing, called owners. Create a random number Series from 15,000 to 73,000.

In [8]:
random_owner_series = np.random.randint(15000, 73001, size=len(cars))
random_owner_series

array([65435, 34331, 24562, 41941, 55369, 28044, 50269, 42205, 71521,
       21066, 61443, 28379, 23109, 44613, 41716, 46294, 22744, 55966,
       65718, 43664, 58462, 50801, 55478, 60282, 68515, 69170, 40968,
       64258, 17344, 22176, 47840, 33934, 27768, 70583, 52130, 50780,
       15492, 39809, 26364, 46854, 25119, 28997, 19416, 59777, 20966,
       45520, 50985, 60517, 33975, 32155, 19887, 39415, 28889, 17196,
       62697, 22889, 15183, 51933, 62285, 59580, 67508, 21067, 61889,
       72628, 65804, 59470, 44358, 29268, 41024, 58618, 49017, 51899,
       37753, 38920, 66928, 43594, 55452, 24646, 59682, 16232, 37163,
       33570, 64950, 36550, 47890, 52204, 55134, 47964, 46293, 63389,
       33930, 20612, 24797, 67005, 20004, 28131, 38095, 50307, 44848,
       40875, 48943, 26854, 25879, 71699, 17656, 45853, 70336, 24654,
       33528, 45286, 67743, 51175, 22605, 69869, 66742, 23684, 56421,
       22251, 43305, 54479, 72624, 68465, 19170, 34271, 25602, 28036,
       47394, 70534, 34815, 69720, 21011, 35294, 36348, 42559, 28979,
       32369, 64327, 66306, 19172, 32980, 59037, 61435, 55649, 32233,
       28277, 20391, 18180, 45480, 15202, 28710, 40553, 57462, 24171,
       27579, 23171, 45263, 61896, 32981, 23355, 66886, 72795, 55008,
       71449, 17418, 64809, 59146, 44572, 64615, 53752, 42427, 36476,
       56712, 70981, 52177, 24069, 27008, 21420, 15202, 27278, 22186,
       72161, 62727, 42673, 64262, 50173, 64168, 34410, 48388, 54398,
       39296, 33768, 59587, 47837, 67580, 40792, 17664, 26998, 67338,
       24330, 66592, 71504, 45135, 40563, 58822, 22616, 64974, 69916,
       32473, 51720, 21227, 54627, 69583, 68101, 69774, 52931, 50192,
       65597, 57556, 33602, 38936, 33880, 32649, 68648, 34400, 39233,
       51567, 18687, 27934, 49216, 28285, 58966, 69467, 67433, 19829,
       28053, 65125, 68867, 57992, 18439, 20548, 19172, 56314, 46222,
       39176, 58381, 57351, 58840, 64555, 69934, 40077, 22595, 34239,
       66658, 29989, 65929, 72524, 52478, 65464, 48137, 43056, 46039,
       18581, 45608, 16759, 29535, 33266, 58735, 44772, 40067, 56441,
       42368, 26261, 58147, 24318, 50240, 66595, 70534, 61907, 41515,
       66753, 40412, 70368, 16557, 54818, 27277, 64974, 66946, 37850,
       57808, 31832, 25068, 23190, 58029, 24824, 27449, 68380, 15033,
       58402, 18833, 50225, 36188, 30603, 68762, 19534, 27481, 48962,
       65257, 56930, 50237, 62019, 58427, 27190, 37069, 19998, 17765,
       41563, 71535, 66659, 44050, 28780, 64392, 60232, 37822, 72173,
       24312, 55072, 22817, 18604, 26635, 17937, 48225, 28245, 32215,
       17487, 67773, 32271, 44709, 68850, 32548, 22618, 19304, 55461,
       17481, 38968, 57100, 17356, 35088, 47171, 17889, 54820, 36939,
       47000, 68796, 65011, 49323, 26893, 22696, 67259, 35518, 72875,
       72492, 70793, 45437, 17472, 60082, 57955, 59249, 58432, 52394,
       69541, 53847, 52433, 64145, 41025, 17003, 47447, 20294, 56385,
       62612, 63744, 15616, 40606, 66785, 29782, 59571, 24690, 67513,
       51594, 29960, 23784, 19749, 44417, 45619, 39836, 67946, 30664,
       70252, 68149])

### Step 8. Add the column owners to cars

In [9]:
cars["owners"] = random_owner_series
cars.head()

,mpg,cylinders,displacement,horsepower,weight,acceleration,model,origin,car,owners
0,18.0,8,307,130,3504,12.0,70,1,chevrolet chevelle malibu,65435
1,15.0,8,350,165,3693,11.5,70,1,buick skylark 320,34331
2,18.0,8,318,150,3436,11.0,70,1,plymouth satellite,24562
3,16.0,8,304,150,3433,12.0,70,1,amc rebel sst,41941
4,17.0,8,302,140,3449,10.5,70,1,ford torino,55369