# Occupation

### Introduction:

Special thanks to: https://github.com/justmarkham for sharing the dataset and materials.

### Step 1. Import the necessary libraries

In [1]:
import pandas as pd

### Step 2. Import the dataset from this [address](https://raw.githubusercontent.com/justmarkham/DAT8/master/data/u.user).

In [2]:
url = ("https://raw.githubusercontent.com/justmarkham/DAT8/master/data/u.user")

### Step 3. Assign it to a variable called users.

In [3]:
users = pd.read_csv(url, sep="|")
users.head()

   user_id  age gender  occupation zip_code
0        1   24      M  technician    85711
1        2   53      F       other    94043
2        3   23      M      writer    32067
3        4   24      M  technician    43537
4        5   33      F       other    15213

### Step 4. Discover what is the mean age per occupation

In [4]:
users.groupby("occupation")["age"].mean()

occupation
administrator    38.746835
artist           31.392857
doctor           43.571429
educator         42.010526
engineer         36.388060
entertainment    29.222222
executive        38.718750
healthcare       41.562500
homemaker        32.571429
lawyer           36.750000
librarian        40.000000
marketing        37.615385
none             26.555556
other            34.523810
programmer       33.121212
retired          63.071429
salesman         35.666667
scientist        35.548387
student          22.081633
technician       33.148148
writer           36.311111
Name: age, dtype: float64

### Step 5. Discover the Male ratio per occupation and sort it from the most to the least

In [5]:
male = users.groupby("occupation")["gender"]
male_ratio = male.apply(lambda x: (x == "M").mean()) * 100
male_ratio.sort_values(ascending=False)

occupation
doctor           100.000000
engineer          97.014925
technician        96.296296
retired           92.857143
programmer        90.909091
executive         90.625000
scientist         90.322581
entertainment     88.888889
lawyer            83.333333
salesman          75.000000
educator          72.631579
student           69.387755
other             65.714286
marketing         61.538462
writer            57.777778
none              55.555556
administrator     54.430380
artist            53.571429
librarian         43.137255
healthcare        31.250000
homemaker         14.285714
Name: gender, dtype: float64

### Step 6. For each occupation, calculate the minimum and maximum ages

In [6]:
users.groupby("occupation")["age"].agg(["min", "max"])

               min  max
occupation
administrator   21   70
artist          19   48
doctor          28   64
educator        23   63
engineer        22   70
entertainment   15   50
executive       22   69
healthcare      22   62
homemaker       20   50
lawyer          21   53
librarian       23   69
marketing       24   55
none            11   55
other           13   64
programmer      20   63
retired         51   73
salesman        18   66
scientist       23   55
student          7   42
technician      21   55
writer          18   60

### Step 7. For each combination of occupation and gender, calculate the mean age

In [7]:
users.groupby(["occupation", "gender"])["age"].mean()

occupation     gender
administrator  F         40.638889
               M         37.162791
artist         F         30.307692
               M         32.333333
doctor         M         43.571429
educator       F         39.115385
               M         43.101449
engineer       F         29.500000
               M         36.600000
entertainment  F         31.000000
               M         29.000000
executive      F         44.000000
               M         38.172414
healthcare     F         39.818182
               M         45.400000
homemaker      F         34.166667
               M         23.000000
lawyer         F         39.500000
               M         36.200000
librarian      F         40.000000
               M         40.000000
marketing      F         37.200000
               M         37.875000
none           F         36.500000
               M         18.600000
other          F         35.472222
               M         34.028986
programmer     F         32.166667
               M         33.216667
retired        F         70.000000
               M         62.538462
salesman       F         27.000000
               M         38.555556
scientist      F         28.333333
               M         36.321429
student        F         20.750000
               M         22.669118
technician     F         38.000000
               M         32.961538
writer         F         37.631579
               M         35.346154
Name: age, dtype: float64

### Step 8.  For each occupation present the percentage of women and men

In [9]:
gender_counts = users.groupby(['occupation', 'gender']).size()
total_counts = users.groupby('occupation').size()
gender_percent = (gender_counts / total_counts * 100).unstack()
gender_percent.round(2)

gender             F       M
occupation
administrator  45.57   54.43
artist         46.43   53.57
doctor           NaN  100.00
educator       27.37   72.63
engineer        2.99   97.01
entertainment  11.11   88.89
executive       9.38   90.62
healthcare     68.75   31.25
homemaker      85.71   14.29
lawyer         16.67   83.33
librarian      56.86   43.14
marketing      38.46   61.54
none           44.44   55.56
other          34.29   65.71
programmer      9.09   90.91
retired         7.14   92.86
salesman       25.00   75.00
scientist       9.68   90.32
student        30.61   69.39
technician      3.70   96.30
writer         42.22   57.78